* Tøm alt
** Samle løsark og spredt materiell [0%]
Samle sammen alle visittkort, kvitteringer og ulikt papirbasert materiale i innboksen.
- [ ] Inn-folder i ryggsekken
- [ ] Innboks BV9
- [ ] Innboks hjemme
- [ ] Postkassen
- [ ] Kvitteringer i bilen
- [ ] Løse papirer som ligger og slenger
** Behandle innboksen til den er tom [0%]
Behandle ferdig alt uferdig papirmateriale, journaler og møtenotater, beskjeder på telefonsvarer, diktafon og eposter.
- [ ] Email NG
- [ ] Email Nellon
- [ ] Email UiO
- [ ] Google Keep
- [ ] Google Photos siden forrige review
- [ ] Assigned issues i Jira
- [ ] Mentions i Jira
- [ ] Assigned issues i Remedy
- [ ] Moleskine
- [ ] Innboks (papirer)
- [ ] Innboksen i Evernote
- [ ] Møtenotater (agenda-view)
- [ ] Inbox.org
** Tøm hodet [0%]
Skriv ned og behandle alle nye prosjekter som ikke er samlet, saker som krever neste handlig, ventende saker, engang-kanskje og lignende.
[[~/.emacs.d/templates/pro-trigger.org][Professional trigger list]]
[[~/.emacs.d/templates/priv-trigger.org][Private trigger list]]
- [ ] Gå gjennom triggerlistene
- [ ] Prosesser det som dukker opp
* Kom deg ajour
** Se gjennom listene over neste handlinger [0%]
Kryss av fullførte handlinger. Se gjennom påminnelser om flere =NEXT-ACTION= som skal skrives ned.
- [ ] Refile tasks
- [ ] Sett avsluttede =NEXT-ACTIONS= til =DONE=
- [ ] Lag påminnelser hvis nødvendig
** Se gjennom tidligere avtaler i kalenderen [0%]
Gå gjennom tidligere avtaler i kalenderen for å finne flere saker som trenger handling, referansedata osv., og flytt disse over i det aktive systemet.
- [ ] NG-kalender
- [ ] Møtereferater
- [ ] Annet referansemateriale
- [ ] Nellon-kalender
** Se gjennom kommende avtaler i kalenderen [0%]
Se gjennom kommende avtaler i kalenderen og samle løse tråder som dukker opp. Fang opp =NEXT-ACTION= som trigges.
- [ ] NG Calendar
- [ ] Nellon Calendar
- [ ] Ticker-file i Evernote
** Se gjennom venter-på listen [0%]
Beslutt hvilke ting du skal følge opp denne uken, kryss av for ting som er utførte.
- [ ] Fått oppdateringer?
- [ ] Opprett =NEXT-ACTION= hvis nødvendig
** Revidere prosjekt og viktige utfall [0%]
Evaluer status for prosjekter, målsetninger og utfall.
Se over en etter en og sørg for å ha minst én neste handling for hvert prosjekt.
Se gjennom prosjektplaner, støttemateriale og annet materiale som er under arbeid og som kan sette i sving nye neste handlinger, venter på osv.
_Grundig vurdering av hvert prosjekt!_
- [ ] Prosjekter som sitter fast?
- [ ] Opprett =NEXT-ACTION=
- [ ] Arkiver fullførte prosjekter
- [ ] Bla gjennom prosjektmateriale i OneNote
- [ ] Bla gjennom prosjektmateriale i Evernote
- [ ] Bla gjennom prosjektmateriale i Org
- [ ] Bla gjennom fysisk prosjektmateriale
** Revidere alle relevante sjekklister
Bruk disse for å få satt i sving nye handlinger.
* Vær kreativ
** Se over engang-kanskje
Revider =SOMEDAY= som nå kan ha blitt aktive og overfør dem til =PROJECT=. Slett saker som har mistet interesse.
- [ ] Aktiver =PROJECT=
- [ ] Sett uinteressante til =CANCELED=
** Vær kreativ og modig
Har du nye, fantastiske, kreative, tankevekkende og risikable ideer som kan føres inn i systemet?
