* Weekly Review %U
  Clock in with C-c C-x C-i
  Clock out with C-c C-x C-o
** Get clear
*** Collect loose papers and materials [0/2]
    Gather all accumulated business cards, receipts, and miscellaneous paper-based materials into your in-tray.
    * [ ] In-folder in backpack
    * [ ] Loose papers laying around
*** Get "IN" to zero [0/6]
    Process completely all outstanding paper materials, journal and meeting notes, voicemails, dictation, and emails.
    :PROCESS:
    1. What it it?
    2. Is it actionable?
       - No
	 * Eliminate
	 * File as reference
	 * Someday / maybe
       - Yes multiple steps
	 * Project task list
    3. What is the next action?
       * Done in 2 minutes?
       * Delegate
	 1. Request
	 2. Follow-up
       * Action list
    :END:
    * [ ] Email NG
    * [ ] Email Nellon
    * [ ] Assigned issues in Jira
    * [ ] Mentions in Jira
    * [ ] ORG inboks
    * [ ] In-tray
*** Empty your head [0/2]
    Put in writing and process any uncaptured new projects, action items, waiting for’s, someday maybe’s, etc.
    :TRIGGER-LIST:
    [[~/.emacs.d/templates/pro-trigger.org][Professional trigger list]]
    [[~/.emacs.d/templates/priv-trigger.org][Private trigger list]]
    :END:
    * [ ] Go through trigger list
    * [ ] Set a timer for 5 minutes and write down what's on your mind
** Get current
*** Review Action Lists [0/3]
    Mark off completed actions. Review for reminders of further action steps to record.
    * [ ] Set finished tasks to DONE
    * [ ] Set reminders if necessary
    * [ ] Refine further tasks
*** Review previous calendar data [0/2]
    Review past calendar in detail for remaining action items, reference data, etc., and transfer into the active system.
    * [ ] Meeting minutes
    * [ ] Other reference material
    * [ ] Nellon Calendar
*** Review Upcoming Calendar [0/2]
    Review upcoming calendar events–long and short term. Capture actions triggered
    * [ ] NG Calendar
    * [ ] Nellon Calendar
*** Review Waiting For List [0/2]
    Record appropriate actions for any needed follow-up. Check off received ones.
    * [ ] Received updates?
    * [ ] Set new actions if necessary
*** Review Project (and Larger Outcome) Lists [0/2]
    Evaluate status of projects, goals, and outcomes, one by one, ensuring at least one current action item on each.  
    Browse through project plans, support material, and any other work-in-progress material to trigger new actions, completions, waiting for’s, etc.
    * [ ] Review Project List, is something stuck?
    * [ ] Browse support material
*** Review Any Relevant Checklists
    Use as a trigger for any new actions.
** Get creative
*** Review Someday Maybe List [0/2]
    Review for any projects which may now have become active, and transfer to “Projects.” Delete items no longer of interest.
    * [ ] Activate projects
    * [ ] Set uninteresting projects to CANCELED
*** Be creative and courageous [0/1]
    Any new, wonderful, hare-brained, creative, thought-provoking, risk-taking ideas to add into your system???
    * [ ] Set timer to 5 minutes and start dreaming

